### ISSUE TITLE
delete hacker news post

### ISSUE THREAD

**Issue by ghost** [szabolcsdombi/optimization-demo#2]
this:

https://news.ycombinator.com/item?id=36569736

was posted by:

https://news.ycombinator.com/user?id=cprogrammer1994

which is:

https://github.com/szabolcsdombi

so you posted your own fake headline. its not python making the keys, its C++

**Comment by szabolcsdombi** [comment]
You do not understand what is happening in this post. Here is an explanation for the parts I am confident you misunderstood.

First, the C implementation is providing a python function, so the function is available in Python and works with Python strings.
Second, the pure python implementation is also 99% C implementation:

```py
def py_accept(key: str) -> str:
    return b64encode(sha1((key + '258EAFA5-E914-47DA-95CA-C5AB0DC85B11').encode()).digest()).decode()
```

- [`b64encode`](https://github.com/python/cpython/blob/main/Modules/binascii.c) is implemented in C
- [`sha1`](https://github.com/python/cpython/blob/main/Modules/sha1module.c) is implemented in C
- `str.encode` is implemented in C
- `bytes.decode` is implemented in C

so is my method.

Almost all the popular python extensions, (including numpy, pillow, scipy, tensorflow, ...) use such calling into C++.
If rigorously viewed even pure python libraries call into C just like I proved above.

This is the way Python can be extended. Supported by default and does not need any additional tools like swig, cython or any custom Python build for it.
It is standard.

**Comment by ghost** [comment]
its highly misleading. the headline says:

> Show HN: Python can make 3M+ WebSocket keys per second 

when this is the reality:

> ![Untitled](https://github.com/szabolcsdombi/optimization-demo/assets/126826528/b17935ba-d892-4def-8138-58a721d76e9e)

more accurate would be:

> Show HN: C++ can make 3M+ WebSocket keys per second

at first I thought you were just lying to the readers, but now it seems you are even lying to yourself. you cant write a bunch of C++ code, then make a post saying "Python is super fast!" then point to the Python standard library when confronted. **no one is accusing the Python standard library** of being misleading, because they dont go around making misleading article titles like the one you did.

if the Python maintainers went around saying `b64encode` is implemented in Python and super fast! then it would be an accurate comparison.

**Comment by szabolcsdombi** [comment]
The tilte is correct. **Python can make 3M+ WebSocket keys per second**. Below you find why.
The title _you_ suggested is way of by a factor of 2x as C++ without any Python wrapper involved can make 7.5M+ (just measured my `sec_websocket_accept()` alone).

If I released this library on PyPI (similar to my [moderngl](https://github.com/moderngl/moderngl), [zengl](https://github.com/szabolcsdombi/zengl), ...) then anyone could install it with pip, do 3M+ websocket keys per second in their "pure python" code without knowing they call into C.

**Comment by ghost** [comment]
> pure python

https://youtube.com/watch?v=dTRKCXC0JFg
